spring:
  application:
    name: wcc-backend

file:
  storage:
    directory: /app/data

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
  paths-to-match: /api/cms/v1/**, /api/platform/v1/**
