name: Scheduled Playwright API Tests against Dev Env

on:
  pull_request_target:
    branches:
      - main
  pull_request:
    branches:
      - main

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs daily at midnight UTC
#   workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    environment: DEV  
    steps:
      - name: Print Debug Info
        run: env | grep "API" || echo "No API variables found"
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set Environment Variables
        run: |
          echo "API_HOST=https://wcc-backend.fly.dev" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.SECURITY_API_KEY }}" >> $GITHUB_ENV
      - name: Install Dependencies
        working-directory: ./integration-test
        run: npm ci
      - name: Run Playwright API Tests
        working-directory: ./integration-test
        run: |
          npm run test-dev || echo "Tests failed" > test-failure.log

      - name: Debug Playwright Report Directory
        run: ls -l ./integration-test/playwright-report || echo "No report found"

      - name: Upload Playwright Report on Failure
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./integration-test/playwright-report/
          retention-days: 30

      - name: Upload Failure Logs (if any)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-failure-log
          path: ./integration-test/test-failure.log
          retention-days: 7